// Generated by Selenium IDE
import com.codeborne.selenide.Browser;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.Sleeper;

import java.util.*;

public class BadTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    System.out.println("--------------------------------------------");
  }

  @Test
  public void test() {
    driver.get("https://ok.ru/");
    driver.manage().window().setSize(new Dimension(1552, 832));
    driver.findElement(By.id("field_email")).sendKeys("alexkworker@mail.ru");
//    driver.findElement(By.id("field_password")).sendKeys("qwerty_6543210", Keys.ENTER);
    driver.findElement(By.xpath("//i[@class = 'tico_img __clean social-icon __s __vk_id']")).click();
    try {
      Thread.sleep(4000);
    } catch (Exception ex){}
    List<String> handles = driver.getWindowHandles().stream().toList();
//    driver.switchTo().window("VK ID");      DOESN'T WORK!
    driver.switchTo().window(handles.get(1));
    driver.findElement(By.name("phone")).sendKeys("9501871983");
  }
}
